steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh baitana \
          --zone=asia-southeast2-a \
          --project=keen-airlock-461707-u8 \
          --tunnel-through-iap \
          --strict-host-key-checking=no \
          --quiet \
          --impersonate-service-account=566492197793-compute@developer.gserviceaccount.com \
          --command='
            set -ex

            # Hapus versi Node.js lama jika ada konflik
            sudo apt-get remove -y nodejs npm || true

            # Tambahkan NodeSource PPA untuk Node.js v20
            # Ini adalah cara standar untuk mendapatkan versi Node.js terbaru di Debian/Ubuntu
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        
            # Instal Node.js dan npm
            sudo apt-get install -y nodejs

            # Lanjutkan Deployment Aplikasi
            cd /var/www/baitana

            git config --global --add safe.directory /var/www/baitana

            if [ -d ".git" ]; then
              git checkout dev || git checkout -b dev
              git pull origin dev
            else
              git clone --branch dev https://github.com/mchardians/baitana.git .
            fi
        
            npm install
            npm run build

            if pm2 list | grep -q "baitana"; then
              pm2 stop baitana
              pm2 delete baitana
            fi
            pm2 start npm --name "baitana" -- start
          '
options:
  logging: CLOUD_LOGGING_ONLY