steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh baitana \
          --zone=asia-southeast2-a \
          --project=keen-airlock-461707-u8 \
          --tunnel-through-iap \
          --strict-host-key-checking=no \
          --quiet \
          --command='
            set -ex

            cd /var/www/baitana

            git config --global --add safe.directory /var/www/baitana

            if [ -d ".git" ]; then
              git checkout dev || git checkout -b dev
              git pull origin dev
            else
              git clone --branch dev https://github.com/mchardians/baitana.git .
            fi

            # Gunakan node dan npm sistem (bukan dari nvm atau /opt/nodejs)
            /usr/bin/node -v
            /usr/bin/npm -v

            /usr/bin/npm install
            /usr/bin/npm run build

            if pm2 list | grep -q "baitana"; then
              pm2 stop baitana
              pm2 delete baitana
            fi

            pm2 start /usr/bin/npm --name "baitana" -- start
          '
options:
  logging: CLOUD_LOGGING_ONLY
